### PR TITLE
Use Cake's IFileSystem for read/write operations instead of System.IO.File

### LINKED ISSUE #117: Aliases bypass Cake's IFileSystem
## Expected Behavior

When using a mock implementation of `IFileSystem` for testing a task that uses Cake.FileHelpers, the mocked file system is being used.

## Current Behavior

Even though the `ICakeContext` passed to the File* aliases uses a mock implementation of `IFileSystem`, the current machine's real file system is used.

## Possible Solution

Adapt the aliases provided by Cake.FileHelpers to avoid using `System.IO.File` and instead use the `IFileSystem` of the current `ICakeContext`.

## Steps to Reproduce (for bugs)

The following example shows a test that should succeeds but instead fails with a `DirectoryNotFoundException`.
(The source code for `FakeCakeContext` can be found [here](https://github.com/ap0llo/shared-build/blob/master/src/SharedBuild.Test/Mocks/FakeCakeContext.cs))

```cs
public class FileHelpersTest
{
    [Fact]
    public void FileReadText_returns_expected_content()
    {
        // ARRANGE
        var path = (FilePath)"X:\\SomeFile.txt";
        var context = new FakeCakeContext();
        context.FileSystem.CreateFile(path).SetContent("Hello World");

        // ACT 
        var content = context.FileReadText(path);

        // ASSERT
        Assert.Equal("Hello World", content);
    }
}
```

## Context

I am writing tests for Cake (Frosting) tasks that use "Cake.FileHelpers" and would like to use the `FakeFileSystem` class from the "Cake.Testing" package to mock the file system used by the tasks.

## Your Environment

* Addin version used: 6.0.
* Cake Version used: 3.0.0
* Operating System: Windows 11

### PR DESCRIPTION
**Pull request by ap0llo**
## Description

In all file aliases, use Cake's IFileSystem abstraction instead of using System.IO.File. 
This enables testing of tasks that use the file aliases by mocking IFileSystem.

The FileTouch() alias continues to use System.IO.File since there is no API in IFileSystem that allows setting the last write time.

## Related Issue
This PR fixes #117

## Motivation and Context
See #117. This enables mocking of the file system in tests for tasks

## How Has This Been Tested?
All tests in the project are still passing

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes. (*Covered by existing tests*)
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/Cake.FileHelpers/FileHelpers.cs [hunk 1]
```diff
@@ -741,6 +729,44 @@ public static Group FindRegexMatchGroupInFile(this ICakeContext context, FilePat
 
             return null;
         }
+
+
+        private static StreamReader CreateStreamReader(ICakeContext context, FilePath file, Encoding? encoding = null)
```
Comment (augustoproiete) [inline src/Cake.FileHelpers/FileHelpers.cs:734]:
```suggestion

        private static StreamReader CreateStreamReader(ICakeContext context, FilePath file, Encoding encoding = null)
```

We don't yet support nullable references in this addin, so let's remove these for now.

File: src/Cake.FileHelpers/FileHelpers.cs [hunk 2]
```diff
@@ -741,6 +729,44 @@ public static Group FindRegexMatchGroupInFile(this ICakeContext context, FilePat
...
+        {
+            var stream = context.FileSystem.GetFile(file).OpenRead();
+            return encoding is null
+                ? new StreamReader(stream, leaveOpen: false)
+                : new StreamReader(stream, encoding, leaveOpen: false);
+        }
+
+        private static StreamWriter CreateStreamWriter(ICakeContext context, FilePath file, FileMode mode, Encoding? encoding = null)
```
Comment (augustoproiete) [inline src/Cake.FileHelpers/FileHelpers.cs:742]:
```suggestion
        private static StreamWriter CreateStreamWriter(ICakeContext context, FilePath file, FileMode mode, Encoding encoding = null)
```

We don't yet support nullable references in this addin, so let's remove these for now.

File: src/Cake.FileHelpers/FileHelpers.cs [hunk 3]
```diff
@@ -741,6 +729,44 @@ public static Group FindRegexMatchGroupInFile(this ICakeContext context, FilePat
 
             return null;
         }
+
+
+        private static StreamReader CreateStreamReader(ICakeContext context, FilePath file, Encoding? encoding = null)
+        {
+            var stream = context.FileSystem.GetFile(file).OpenRead();
```
Comment (augustoproiete) [inline src/Cake.FileHelpers/FileHelpers.cs:736]:
```suggestion
            var stream = context.FileSystem.GetFile(file.MakeAbsolute(context.Environment)).OpenRead();
```

Let's expand the path to an absolute path to keep the original behavior that is now removed from the aliases

File: src/Cake.FileHelpers/FileHelpers.cs [hunk 4]
```diff
@@ -741,6 +729,44 @@ public static Group FindRegexMatchGroupInFile(this ICakeContext context, FilePat
...
+            return encoding is null
+                ? new StreamReader(stream, leaveOpen: false)
+                : new StreamReader(stream, encoding, leaveOpen: false);
+        }
+
+        private static StreamWriter CreateStreamWriter(ICakeContext context, FilePath file, FileMode mode, Encoding? encoding = null)
+        {
+            var stream = context.FileSystem.GetFile(file).Open(mode);
```
Comment (augustoproiete) [inline src/Cake.FileHelpers/FileHelpers.cs:744]:
```suggestion
            var stream = context.FileSystem.GetFile(file.MakeAbsolute(context.Environment)).Open(mode);
```

Let's expand the path to an absolute path to keep the original behavior that is now removed from the aliases

**Review by augustoproiete — CHANGES_REQUESTED** [review]
Thanks for the PR @ap0llo! Concept ACK and overall LGTM. Added a couple of minor comments/requests

**Comment by ap0llo** [comment]
Thanks for your review! I applied your suggestions, please let me know if there is anything else you'd like me to adapt.

**Review by augustoproiete — APPROVED** [review]
LGTM
